on: [push]

jobs:
  decision-tree:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: decision-tree
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - run: |
          dotnet restore
          dotnet tool restore
      - run: dotnet build
      - run: dotnet tool run fantomas --check .
      - run: dotnet tool run dotnet-fsharplint lint DecisionTree.fsproj
      - run: dotnet test

  dijkstra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dijkstra
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - run: go build -v
      - run: test -z $(gofmt -l .)
      - run: go test -v

  dug:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dug
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.x
      - run: pip install -r requirements.txt
      - run: |
          black --check .
          isort -c .
      - run: |
          pylint $(find . -type f -name '*.py')
          pyright .
      - run: pytest .

  genetic:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: genetic
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.x
      - run: pip install -r requirements.txt
      - run: |
          black --check .
          isort -c .
      - run: |
          pylint genetic test
          pyright .
      - run: pytest .
