name: CI

on: [push]

jobs:
  blockchain:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: blockchain/old
    steps:
      - uses: actions/checkout@v2
      - name: yarn install
        run: yarn install
      - name: yarn run test
        run: yarn run test

  decision-tree-player:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: decision-tree-player
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "15"
      - name: gradle test
        run: gradle test

  dijkstra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dijkstra
    steps:
      - uses: actions/checkout@v2
      - name: yarn install
        run: yarn install
      - name: yarn run lit
        run: yarn run lint
      - name: yarn run test
        run: yarn run test

  geneticalgorithm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: geneticalgorithm
    steps:
      - uses: actions/checkout@v2
      - name: go test
        run: go test ./...

  oop-limitations:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: oop-limitations
    steps:
      - uses: actions/checkout@v2
      - name: dotnet test
        run: dotnet test
