name: CI

on: [push]

jobs:
  blockchain:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: blockchain
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Install
        run: dotnet tool restore
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test
      - name: Format
        run: dotnet tool run fantomas --check .
      - name: Lint
        run: dotnet tool run dotnet-fsharplint lint Blockchain.fsproj

  decision-tree-player:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: decision-tree-player
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install
        run: dotnet tool restore
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test
      - name: Format
        run: dotnet tool run fantomas --check .
      - name: Lint
        run: dotnet tool run dotnet-fsharplint lint Blockchain.fsproj

  dijkstra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dijkstra
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test

  genetic-algorithm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: genetic-algorithm
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: 1.1.10
      - name: Install
        run: poetry install
      - name: Lint
        run: poetry run pylint --rcfile='.pylintrc' genetic_algorithm test && poetry run mypy genetic_algorithm test
      - name: Format
        run: poetry run black --check .
      - name: Test
        run: poetry run pytest .
