on: [push]

jobs:
  decision-tree:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: decision-tree
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - run: dotnet restore
      - run: dotnet build
      - run: |
          dotnet new tool-manifest
          dotnet tool install fantomas-tool
          dotnet fantomas --check .
      - run: dotnet test

  dijkstra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dijkstra
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - run: go build -v
      - run: test -z $(gofmt -l .)
      - run: go test -v

  genetic:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: genetic
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - run: dotnet restore
      - run: dotnet build
      - run: |
          dotnet new tool-manifest
          dotnet tool install csharpier
          dotnet dotnet-csharpier --check .

  reportus:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: reportus
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.x
          cache: pip
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - run: black --check .
      - run: isort -c .
      - run: ruff check .
      - run: pyright .
      - run: pytest asmt
      - run: playwright install-deps && playwright install chromium
      - run: pytest e2e

  reportus-deploy:
    needs: reportus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - shell: pwsh
        run: |
          Get-ChildItem -Force `
          | Where-Object { -not ($_.Name -eq '.git' -or $_.Name -eq 'reportus') } `
          | ForEach-Object { Remove-Item -Force -Recurse $_.Name }
          Get-ChildItem -Force reportus `
          | Move-Item -Destination . -Force
          Remove-Item reportus
          git checkout -b st
          git add -A
          git config user.name 'brunoroque06'
          git config user.email 'brunoroque06@github.com'
          git commit -m 'Release'
          git push --force origin st
