name: CI

on: [push]

jobs:
  blockchain:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: blockchain
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Install
        run: dotnet tool restore
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test
      - name: Format
        run: dotnet tool run fantomas --check .
      - name: Lint
        run: dotnet tool run dotnet-fsharplint lint Blockchain.fsproj

  decision-tree-player:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: decision-tree-player
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "15"
      - name: Test
        run: gradle test

  dijkstra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dijkstra
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.9.0
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm run lint
      - name: Test
        run: pnpm run test

  genetic-algorithm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: genetic-algorithm
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install
        run: pip install -r requirements.txt
      - name: Lint
        run: pylint --rcfile='.pylintrc' genetic_algorithm test && mypy genetic_algorithm test
      - name: Format
        run: black --check
      - name: Test
        run: pytest .

  oop-limitations:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: oop-limitations
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Test
        run: dotnet test
