name: CI

on: [push]

jobs:
  ci:
    strategy:
      matrix:
        proj: [decision-tree, dijkstra, dug, genetic]
    runs-on: ubuntu-latest
    steps:
      - run: curl -L https://dl.dagger.io/dagger-cue/install.sh | sh
        working-directory: /usr/local
      - uses: actions/checkout@v3
      - run: dagger-cue project init && dagger-cue project update
      - run: dagger-cue do ${{ matrix.proj }}
