name: CI

on: [push]

jobs:
  blockchain:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: blockchain
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: dotnet tool restore
      - name: Format
        run: dotnet tool run fantomas --check .
      - name: Lint
        run: dotnet tool run dotnet-fsharplint lint Blockchain.fsproj

  decision-tree-player:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: decision-tree-player
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "15"
      - name: Test
        run: gradle test

  dijkstra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dijkstra
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn install
      - name: Lint
        run: yarn run lint
      - name: Test
        run: yarn run test

  genetic-algorithm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: genetic_algorithm
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: pip install -r requirements.txt
      - name: Lint
        run: pylint . && mypy .
      - name: Format
        run: black --check
      - name: Test
        run: pytest .

  oop-limitations:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: oop-limitations
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: dotnet test
